# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languages',
            new_name='language',
        ),
    ]
